- Rakefile
This avoids getting all the commits while we only need the latest version of the whole codebase.
> *Rakefile: Shallow clone mruby

- src/mrb_redis.c
The allocated redis context wasn't garbage collected.
Also fixed a possible double free issue in ```Redis#close```
> enable garbage collection for redis context

- .gitignore
- include/mruby/redis.h
- mrblib/error.rb
- src/mrb_redis.c
- test/redis.rb
This adds three new commands:
- ```Redis#queue```
- ```Redis#reply```
- ```Redis#bulk_reply```
```Redis#queue``` queues a single Redis command, ```Redis#reply``` gets a single reply back and ```Redis#bulk_reply``` gets all queued Redis commands back.
> added Pipelining

- mrbgem.rake
Hi, I failed compile error under the OS X.
`HIREDIS` is now version 1.0, 1.0 not compatible under the OS X.
I got a below error.
```
build: [exec] git clone git://github.com/redis/hiredis.git
Cloning into 'hiredis'...
build: [exec] make
make[1]: warning: jobserver unavailable: using -j1.  Add `+' to parent make rule.
clang -g -std=gnu99 -O3 -Wall -Werror-implicit-function-declaration -Wdeclaration-after-statement -Wwrite-strings -std=c99 -pedantic -c -O3 -fPIC  -Wall -W -Wstrict-prototypes -Wwrite-strings -g -ggdb  net.c
net.c:139:37: error: use of undeclared identifier 'TCP_KEEPALIVE'
if (setsockopt(fd, IPPROTO_TCP, TCP_KEEPALIVE, &val, sizeof(val)) < 0) {
^
net.c:433:29: error: use of undeclared identifier 'AF_LOCAL'
if (redisCreateSocket(c,AF_LOCAL) < 0)
^
net.c:458:21: error: use of …
```
> Fix compile error under OS X

- src/mrb_redis.c
I got below error when I add `fPIC` to cflags.
```
/ngx_mruby/mruby/build/mrbgems/mruby-redis/src/mrb_redis.c:969:3: error: 'for' loop initial declarations are only allowed in C99 or C11 mode
for (mrb_int argc_current = 1; argc_current < argc; argc_current++) {
^
rake aborted!
Command failed with status (1): [gcc-4.9  -fPIC -DPIC -DMRBGEM_MRUBY_REDIS_...]
```
This PR avoids `error: 'for' loop initial declarations `.
> declare before for_loop to compatibility

- src/mrb_redis.c
- test/redis.rb
ref:
* http://redis.io/commands/hmget
* http://redis.io/commands/hmset
> Implement Redis#HMGET and Redis#HMSET

- src/mrb_redis.c
- test/redis.rb
This PR adds tests for existing features.
While trying to cover `publish`, I noticed there was a discrepancy between what it actually returns (the redis object itself) and what Redis was actually returning (number of subscribed clients that received the messages), so I changed the behavior to match with the actual Redis implementation.
> Add tests and correct behaviors

- README.md
- src/mrb_redis.c
- test/redis.rb
This PR implements `PF*` commands, utilizing HyperLogLog data structures in Redis:
* `PFADD hll foo` : Add an element
* `PFCOUNT hll` : Count (implicitly distinct) elements
* `PFMERGE hll3 hll1 hll2` : Merge two HLL data structures together
Also, `Redis#flushall` became handy so I added it to the mix (in a separate commit).
> Add support for PF* commands

- test/redis.rb
The name of `assert("Redis#pfcount")` is duplicated. The latter seems to be Redis#pfcount, so I changed the assert name.
> Fix assert name s/pfcount/pfmerge/

- src/mrb_redis.c
* Redis#pfcount in current implementation needs 2 elements just like "PDCOUNT key". The number of elements in argv was one extra.
* Redis#pfmerge in current implementation needs 4 elements just like "PDMERGE dest src1 src2". The number of elements in argv was not enough one.
> Fix the number of elements in pfcount and pfmerge

- src/mrb_redis.c
'for' loop initial declarations are only allowed in C99 or C11 mode.
[ngx_mruby](https://github.com/matsumoto-r/ngx_mruby) fails to test like the following: https://travis-ci.org/hfm/ngx_mruby/jobs/153750690#L1048-L1071
> Fix: Declare valiables outside of for-loop

- src/mrb_redis.c
- test/redis.rb
I reimplemented Redis#pf* methods.
- Allow [Redis#pfadd](http://redis.io/commands/pfadd) to specify multiple elementns.
- Allow [Redis#pfcount](http://redis.io/commands/pfcount) to add multiple keys.
- Allow [Redis#pfmerge](http://redis.io/commands/pfmerge) to add multiple sourcekeys.
> Allow Redis#pf* to add multiple arguments.

- src/mrb_redis.c
> Fix a part of declaration-after-statement warnings in hmget and hmset

- src/mrb_redis.c
- test/redis.rb
in redis protocol, set argument is below.
SET key value [EX seconds] [PX miliseconds] [NX|XX]
We make Redis#set  accept EX, PX and NX|XX.
> Add Redis#set option value [EX seconds] [PX miliseconds] [NX|XX]

- src/mrb_redis.c
When an error occurs, redisCommand family (such as redisCommandArgv) return NULL and the err field of redisContext will be set non-zero (not REDIS_OK) value. It should check a value of rc->err for error-handling.
> Check error of redisContext

- mrbgem.rake
- src/mrb_redis.c
See also more information: https://github.com/matsumotory/mruby-pointer
- PoC code
ref: https://github.com/matsumotory/mruby-pointer#example
```c
mrb_src = mrb_open();
mrb_dst = mrb_open();
mrb_udptr_init(mrb_src);
mrb_load_string(mrb_src, 'Redis.connect_set_raw "127.0.0.1", 6379');
mrb_udptr_copy(mrb_src, mrb_dst);
mrb_load_string(mrb_dst, 'redis = Redis.connect_get_raw; p redis["hoge"]');
mrb_udptr_free(mrb_src);
```
> Support shared redis instance between mrb_states

- README.md
- src/mrb_redis.c
- test/redis.rb
This commit adds `SETNX`. `SET` was supporting options but this command
uses the native `SETNX` call instead.
This PR addresses #86
> Implement `SETNX`

- src/mrb_redis.c
- test/redis.rb
I've enhanced argument handling. Currently only `get`/`set` methods are scoped, but can be applied to another methods if this fix works good.
I've done several changes, so seeing separate commits might be more review-friendly :wink:
To be honest, I'm wondering if there were any performance issue that you avoid those handling...:thinking:
If you pass non-string value as key and/or value in `get`/`set` method,
**Before:** Segfault :boom:
:point_down:
**After:** Raises `TypeError` :white_check_mark:
But of course, there are some other choices that I can do:
- Convert everything to string instead of raising error
- Convert symbol to string only for key, and raise error otherwise
- Convert symbol to string only for key, convert everything to string for value, and raise error otherwise
- ...etc …
> Better argument handling in get/set

- include/mruby/redis.h
- src/mrb_redis.c
- test/redis.rb
This fixes #89, but actually it's more drastic change on how the methods call Redis commands.
Previously, each method is implemented independently and do type check, error check or reply conversion on its own responsibility.
Therefore, there exists inconsistency between methods, and some can't handle error well nor return appropriate reply.
Here, I refactored it, and almost all methods utilize same common methods to build command and execute it.
Here's the list of "common methods" (See b63a6707e179d983b95e2118990bea1b5216df5e for more details):
- `mrb_redis_create_command_...`
- Build redis command by parsing args. It's like `CREATE_REDIS_COMMAND_ARGX` macro, but do more (it uses the macro inside).
- Following methods don't use this due to optional arguments:`set`, `hmget`, `hmset`, …
> Refactor for safer method call and consistent return value

- README.md
- mrbgem.rake
- src/mrb_redis.c
- test/redis.rb
```ruby
client = Redis.new 'localhost', 6379
client.enable_keepalive
client.keepalive # => :on
```
Note that we don't support disabling keepalive, simply because hiredis doesn't.
(This is the last one of my series of PRs 😉)
> Add support of TCP keepalive

- mrbgem.rake
Remove `-fPIE` option from `cc.flags` to prevent from link error while building hiredis.
We build ngx_mruby with `-fPIE` option to embed to nginx built with `-pie` option. But passing `-fPIE` option causes link error when creating shared library (`libhiredis.so`) with `-shared` option using older version of gcc like gcc 4.4.
> Remove -fPIE option from cc.flags

- .travis.yml
- README.md
- src/mrb_redis.c
- test/redis.rb
This PR adds Redis#cluster and Redis#asking methods.
It allows sending commands for [Redis Cluster](https://redis.io/topics/cluster-spec) (e.g. [CLUSTER NODES](https://redis.io/commands/cluster-nodes), [CLUSTER SLOTS](https://redis.io/commands/cluster-slots), etc.).
> Support Redis#cluster and Redis#asking methods

- mrbgem.rake
BSD make is not GNU make. I get the following errors on NetBSD.
```
build: [exec] make
make[1]: "/home/vagrant/ngx_mruby/mruby/build/host/mrbgems/mruby-redis/hiredis/Makefile" line 30: Need an operator
make[1]: "/home/vagrant/ngx_mruby/mruby/build/host/mrbgems/mruby-redis/hiredis/Makefile" line 36: Need an operator
make[1]: "/home/vagrant/ngx_mruby/mruby/build/host/mrbgems/mruby-redis/hiredis/Makefile" line 37: Variable/Value missing from "export"
make[1]: "/home/vagrant/ngx_mruby/mruby/build/host/mrbgems/mruby-redis/hiredis/Makefile" line 62: Missing dependency operator
make[1]: "/home/vagrant/ngx_mruby/mruby/build/host/mrbgems/mruby-redis/hiredis/Makefile" line 73: Need an operator
make[1]: "/home/vagrant/ngx_mruby/mruby/build/host/mrbgems/mruby-redis/hiredis/Makefile" line 75: Missing …
```
> Make this build on *BSD.

- mrbgem.rake
When we ran the build with `matsumotory/mruby-redis` included, it failed with the error message.
```
#32 34.94 build: [exec] git clone git://github.com/redis/hiredis.git
#32 35.35 fatal: remote error:
#32 35.35   The unauthenticated git protocol on port 9418 is no longer supported.
#32 35.35 Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
#32 35.35 Cloning into 'hiredis'...
#32 35.36 rake aborted!
#32 35.36 git clone git://github.com/redis/hiredis.git failed
#32 35.36
#32 35.36 (See full trace by running task with --trace)
#32 35.39 make: *** [build_mruby] Error 1
```
This is due to the git protocol (`git://`) used in the command to download redis/hiredis.
https://github.com/matsumotory/mruby-redis/blob/f1f98d9450783b8c281b5064554b12b …
> Change the protocol used to download hiredis from git to https
